[package]
name = "task_utils"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
serde_json = "1.0.140"
anyhow = "1"
serde = { version = "1.0.219", features = ["derive"] }
utils = { path = "../utils" }
